language: generic

sudo: required
services:
 - docker
beofre_install:
  - docker build -t breachlight/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true breachlight/docker-react npm run test